android.useAndroidX=true
android.enableJetifier=true
# Más memoria para el daemon de Gradle
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8 -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError

# (opcional) bajar paralelismo si tu PC sufre
org.gradle.parallel=false
org.gradle.workers.max=2
